sgruhier/foundation_rails_helper

- CHANGELOG.md
- README.md
- lib/foundation_rails_helper/configuration.rb
- lib/foundation_rails_helper/flash_helper.rb
- spec/foundation_rails_helper/configuration_spec.rb
- spec/foundation_rails_helper/flash_helper_spec.rb
This PR adds a config option to specify a blacklist of flash keys to be ignored (fixing #98) 
It also refactors the flash helper to make it more clear and robust
> Allow blacklisting of flash keys which are only used for state

- lib/foundation_rails_helper/form_builder.rb
- spec/foundation_rails_helper/form_builder_spec.rb
I noticed that setting label: false would generate label="false" as attribute on my radio buttons. This fixes it.
> Don't output label="false" on radio_button

- foundation_rails_helper.gemspec
fixes error when using ruby -v 1.9.3
mime-types 3+ is incompatible with 1.9.3
only an issue in development env as mime-types is
a capybara dependency only
> add mime-types as a dev dependency

- README.md
fix typo in call to f.text_field, and prefer "foundation-rails" to "zurb-foundation"
> Improve readme: fix syntax error; change in preferred gem

- foundation_rails_helper.gemspec
- lib/foundation_rails_helper/form_builder.rb
- spec/foundation_rails_helper/form_builder_spec.rb
Updates to the new foundation 6 error classes add adds support for Rails5.0.0.beta3
> Foundation 6

- lib/foundation_rails_helper/flash_helper.rb
- spec/foundation_rails_helper/flash_helper_spec.rb
It makes it so the callout added by flash messages is easier to select with CSS as opposed to callouts already on the page.
> Add "flash" class to callout

- foundation_rails_helper.gemspec
Version 2.7.1 causes check_box tests to break.
> Lock capybara at 2.6

- foundation_rails_helper.gemspec
Version 2.7.1 causes check_box tests to fail
> Lock capybara to v2.6

- spec/foundation_rails_helper/form_builder_spec.rb
Fixes #136
Rails 4 generates datetime fields with `type=datetime`
Rails 5 generates datetime fields with `type=datetime-local`
> (fix): Failing spec under Rails 5

- foundation_rails_helper.gemspec
- spec/foundation_rails_helper/form_builder_spec.rb
Capybara 2.7 introduces behaviour whereby hidden elements are not
recognised (this is sensible since users do not normally interact with
hidden elements).
This caused a problem for a couple of our specs which asserted the
presence of hidden elements.
https://github.com/sgruhier/foundation_rails_helper/pull/133 locked capybara to 2.6 because of failing specs. This PR fixes the failing specs and updates to `~>2.7`
> (chore): upgrade capybara

- .travis.yml
Currently we have both 'build pushes' (build all pushed commits) and
'build PRs' enabled.
This means that for each commit pushed to a PR, the whole thing is built
twice, identically in Travis.
This commit restricts push commits to just those made directly to the
master branch.
Source:
https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda
> Prevent Travis building twice on PRs

- lib/foundation_rails_helper/action_view_extension.rb
- lib/foundation_rails_helper/form_builder.rb
- spec/foundation_rails_helper/form_builder_spec.rb
Fixes #131 
- Removes `alias_method_chain`
- Fixes a separate bug whereby `auto_labels: nil` would be interpreted as false rather than true
> action view extension cleanup

- README.md
The foundation-5 branch will use version 2.x.x, not 1.2.x
> Foundation 5 - Fix version number

- CHANGELOG.md
- lib/foundation_rails_helper/flash_helper.rb
- spec/foundation_rails_helper/flash_helper_spec.rb
Making a breaking change to display_flash_messages that requires the key_matching hash to be prefixed with the :key_matching keyword.
Adding the keyword option :closable to the display_flash_messages method that accepts a boolean true/false, defaulting to true.
If false, suppresses the close buttons on the callouts.
> Adding closable keyword option to display_flash_messages

- lib/foundation_rails_helper/form_builder.rb
#157 Making the `error_for` method in `form_builder` public.
Moving the return statement up at the beginning of the method. No sense
in calculating the class_name if there are no errors for the attribute.
> Making the error_for method public

- .rubocop.yml
- lib/foundation_rails_helper.rb
- lib/foundation_rails_helper/form_builder.rb
- lib/foundation_rails_helper/size_class_calculator.rb
- spec/foundation_rails_helper/form_builder_spec.rb
This PR fixes the case when you have a checkbox with a label that has HTML content (like an accept terms and conditions checkbox with a link to the terms), right now the label is not properly escaped and the link isn't marked as safe.
It also fixes some rubocop offenses so the build is green.
> Fix label output in checkbox when labels have HTML

- foundation_rails_helper.gemspec
To remove warning messages when building gem
> Set a max Rails version of 6.0

- .travis.yml
- README.md
- foundation_rails_helper.gemspec
- spec/support/mock_rails.rb
I expanded the constraint in the gemspec to include Rails 6. There were a few changes to the spec setup that were needed in order for them to run on Rails 6, those changes were backward compatible  with Rails 4 and 5.
I also expanded  the Travis setup:
*  Removed Rails 4.1
*  Added Rails 5.2 and 6.0
*  Updated rubies 2.1 through 2.4 to the most recent patchlevel
*  Added ruby 2.5 and 2.6 for Rails 5 and 6 (6 _requires_ 2.5+)
I think one could be less generous on supported versions -- Rails 4.2 should be EOL now that Rails 6 is out, and ruby 2.2 has been EOL for a little over a year -- but I didn't want to presume.
I think the only thing left is to determine the version number and update the CHANGELOG. I didn't  technically remove Rails 4.1 support, but I did remove it from Travis.
> Rails 6 support

- .travis.yml
- foundation_rails_helper.gemspec
- spec/foundation_rails_helper/form_builder_spec.rb
Hello,
I was working on updating my app to Rails 6.1 and noticed that this gem's version dependency on the "tzinfo" gem was holding me back.
I couldn't see anything in the code that relied on tzinfo — doing some code archaeology, the dependency appears to have been added to keep compatibility with Rails 3 while adding Rails 4 support (and has been periodically bumped since then) — so, I removed the requirement.
While I was here, I updated the Travis config to include Rails 6.1, added Ruby 2.7 to the matrix where supported, and removed Rubies 2.1 and 2.2 which have been EOL for a few years now.
I also found some test failures in Rails 6.1 when using `date_field`, `time_field`, etc. with non-date attributes. Seemed like a thing a "real person" wouldn't do, so I just changed the test.
> Remove dependency on tzinfo gem

- lib/foundation_rails_helper/version.rb
Bumping the gem version to 4.0.1. to emphasize the rails 7 support. 
@sgruhier, can you also make the release available in ruby gems as well?
> Bump version to 4.0.1
